databases:
  - name: moviebookingdb
    plan: free
    databaseName: moviebooking
    user: moviebooking

services:
  - type: web
    plan: free
    name: movie-booking
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'gunicorn movie_booking.wsgi:application'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: moviebookingdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: '.onrender.com'
      - key: WEB_CONCURRENCY
        value: 4